biopragmatics/pyobo

src/pyobo/apps/mapper/cli.py
src/pyobo/getters.py
src/pyobo/registries/metaregistry.json
src/pyobo/struct/struct.py
src/pyobo/xrefdb/sources/__init__.py
src/pyobo/xrefdb/sources/cbms2019.py
src/pyobo/xrefdb/sources/famplex.py
src/pyobo/xrefdb/xrefs_pipeline.py
tests/test_mapper.py

Closes #14
This PR adds the `Canonicalizer` class, whose job it is to figure out which xref for a given CURIE is the best one based on a priority list that the user provides upon instantiation.
This PR also adds some updates to the metaregistry as well as FamPlex as a xref source.

Add CURIE canonicalizer

---

src/pyobo/sources/mesh.py
src/pyobo/sources/pubchem.py
src/pyobo/xrefdb/sources/__init__.py
src/pyobo/xrefdb/sources/pubchem.py

Add pubchem-mesh mappings

---

src/pyobo/registries/metaregistry.json
src/pyobo/sources/__init__.py
src/pyobo/sources/pfam.py
src/pyobo/sources/pfam_clan.py

Closes #21
PFAM doesn't maintain xrefs to InterPro as far as I can tell. I'm not including the uniprot download because its a lot of gigabytes...

Add PFAM and PFAM Clans

---

src/pyobo/sources/__init__.py
src/pyobo/sources/umls/__init__.py
src/pyobo/sources/umls/__main__.py
src/pyobo/sources/umls/synonym_types.tsv
src/pyobo/sources/umls/umls.py
src/pyobo/struct/struct.py

Add UMLS conversion

---

src/pyobo/sources/pubchem.py

Update depricated url ftp from pubchem

Update PubChem dump version

---

src/pyobo/sources/chembl.py
src/pyobo/xrefdb/sources/__init__.py
src/pyobo/xrefdb/sources/chembl.py

Add ChEBML conversion

---

src/pyobo/extract.py
tests/test_alt_ids.py

Fix get name lookup when there are no alts available

---

src/pyobo/sources/itis.py

Automatically parse out ITIS version number

---

.travis.yml
README.rst
setup.cfg
src/pyobo/mocks.py
src/pyobo/normalizer.py
src/pyobo/struct/reference.py
src/pyobo/struct/struct.py
src/pyobo/xrefdb/xrefs_pipeline.py
tests/test_alt_ids.py
tests/test_extract.py
tests/test_get.py
tests/test_ground.py

Closes #76 
CC @aren-lorenson-enveda I started putting together some mocks so I could actually get the PyOBO tests running in Travis as well.

Add mocks, tests, and 3.6 compatibility

---

src/pyobo/getters.py
src/pyobo/path_utils.py
tests/constants.py
tests/test_extract.py
tests/test_get.py

Refactor OBO Loading

---

setup.cfg
src/pyobo/sources/ccle_cell.py

This PR automates downloading the CCLE Cell line information from cBioPortal and creates an OBO file from it.
It is also accompanied with a PR in the Bioregistry (https://github.com/bioregistry/bioregistry/commit/98708d85731139f3c6a91e6ec8e80c873df44ca6)
CC @bgyori @stirlin6

Add CCLE Cells

---

setup.cfg
src/pyobo/sources/depmap.py
src/pyobo/struct/struct.py

This PR adds a converter from the DepMap metadata to OBO
Accompanying updates to bioregistry:
- Added `depmap` https://github.com/bioregistry/bioregistry/commit/b2a8f918ed90b8443d9c2bbf21a078159aa267c0
- Added `cosmic.cell` https://github.com/bioregistry/bioregistry/commit/b41aee6bba01aa5ff0a879f839f17e7c32479c32
CC @bgyori @stirlin6

Add DepMap cell lines

---

src/pyobo/__init__.py
src/pyobo/api/__init__.py
src/pyobo/api/names.py
src/pyobo/cli/lookup.py
src/pyobo/sources/ncbigene.py
src/pyobo/struct/struct.py
src/pyobo/utils/cache.py

This is slightly different than names since there could be terms with no names. Use case: need to get all CCLE cell line names, even though ~25% have no labels

Get list of identifiers

---

docs/source/conf.py
src/pyobo/sources/selventa/__init__.py
src/pyobo/sources/selventa/schem.py
src/pyobo/sources/selventa/scomp.py
src/pyobo/sources/selventa/sdis.py
src/pyobo/sources/selventa/sfam.py
src/pyobo/sources/uniprot/uniprot.py
src/pyobo/struct/struct.py
tox.ini

Closes #26, closes #27, closes #22
This PR adds selventa complexes, families, chemicals, and diseases

Add selventa vocabularies

---

src/pyobo/sources/interpro.py

Fix interpro processing

---

src/pyobo/resources/ncbitaxon.py
src/pyobo/sources/uniprot/uniprot.py

Update UniProt download

---

src/pyobo/sources/mesh.py

There is no key named `["concepts"]` in any dictionary within `descriptor_record` which is a `List[dict]` rather than a `dict` as the code seems to expect.
P.S: @cthoyt

Update MeSH import for 2023+ data

---

src/pyobo/api/xrefs.py
src/pyobo/struct/struct.py

Make adding names to SSSOM optional

---

setup.cfg
src/pyobo/sources/umls/umls.py

This enables querying by parent type

Add UMLS semantic types

---

src/pyobo/getters.py
src/pyobo/sources/__init__.py
src/pyobo/sources/civic_gene.py
src/pyobo/sources/omim_ps.py
src/pyobo/xrefdb/sources/wikidata.py

- Add CiVIC Gene source
- Add OMIM Phenotypic Series getter
- Add context to nobuild error
- Cleanup pystow usage in old wikidata xref code

Add new sources for CiVIC Gene and OMIM Phenotypic series

---

src/pyobo/api/names.py
src/pyobo/sources/rgd.py
src/pyobo/xrefdb/sources/wikidata.py

This PR fixes the URL for the rgd resource file.
See also: https://github.com/biopragmatics/bioversions/pull/44

Fix URL for rgd

---

src/pyobo/sources/umls/get_synonym_types.py
src/pyobo/sources/umls/synonym_types.tsv
src/pyobo/sources/umls/umls.py
src/pyobo/struct/__init__.py
src/pyobo/struct/struct.py

This PR fixes an issue with new UMLS synonym type definitions that have newlines, streamlines processing, and introduces a reusable "default" reference generator

Update UMLS synonym type definition loading

---

pyproject.toml
src/pyobo/sources/civic_gene.py
src/pyobo/sources/hgnc.py

- reuse identifier sort in civic
- better sorting of SO class terms in HGNC

Update civic.gene and hgnc sources

---

src/pyobo/struct/typedef.py

Reuse Reference.from_curie for parsing

Reuse `Reference.from_curie` for parsing in typedefs module

---

src/pyobo/getters.py

- write on each iteration
- pass through strictness annotation
- better warnings on URL errors
- handle drugbank missing credentials in loop

Improve ontology loading utilities

---

src/pyobo/reader.py

This specifically makes it possible to get classyfire

Fix reading from compressed OBOs

---

src/pyobo/identifier_utils.py
src/pyobo/reader.py
tests/test_reader.py

- Remove custom parsing logic from relation and property parsing, replace with Reference.from_curie_or_uri
- Add bioontologies URI upgrading into Reference.from_curie_or_uri
- Reuse bioregistry's identifier standardization code where possible

Further consolidate CURIE/URI parsing

---

src/pyobo/sources/bigg/bigg_compartment.py
src/pyobo/sources/ccle.py
src/pyobo/sources/msigdb.py
src/pyobo/sources/nlm_catalog.py
src/pyobo/sources/ror.py
src/pyobo/struct/typedef.py

This PR makes various improvements to the named sources. E.g., some make it more explicit to support near future Turtle output

Update MSigDB, CCLE, BiGG, NLM, and ROR

---

pyproject.toml
src/pyobo/struct/reference.py
src/pyobo/struct/struct.py
src/pyobo/struct/typedef.py
src/pyobo/struct/utils.py
tests/test_struct.py
tests/test_typedef.py

1. Add a lot of missing fields
2. Refactor the way axioms work

Refactor term and typedef models

---

src/pyobo/api/hierarchy.py
src/pyobo/api/properties.py
src/pyobo/api/relations.py
src/pyobo/reader.py
src/pyobo/struct/reference.py
src/pyobo/struct/struct.py
src/pyobo/struct/struct_utils.py
src/pyobo/struct/typedef.py
src/pyobo/struct/vocabulary.py
tests/test_reader.py
tests/test_struct.py
tests/test_typedef.py

This also includes refactoring to excise shared functionality and implementation between the term and typedef stanzas

Implement `intersection_of`

---

pyproject.toml
src/pyobo/api/alts.py
src/pyobo/api/hierarchy.py
src/pyobo/api/names.py
src/pyobo/constants.py
src/pyobo/getters.py
src/pyobo/utils/cache.py
tests/test_alt_ids.py

This is useful for testing purposes

Add flag for turning off caching

---

src/pyobo/api/alts.py
src/pyobo/api/names.py
src/pyobo/api/species.py
src/pyobo/api/utils.py
src/pyobo/struct/struct_utils.py
tests/test_api.py

More consistently use the prefix/identifier handler function

Refactor reference passing

---

src/pyobo/api/properties.py
src/pyobo/reader.py
src/pyobo/sources/ror.py
src/pyobo/struct/functional/obo_to_functional.py
src/pyobo/struct/reference.py
src/pyobo/struct/struct.py
src/pyobo/struct/struct_utils.py
tests/test_obo_reader/test_reader.py
tests/test_struct/test_obo/test_struct_term.py
tests/test_struct/test_obo/test_typedef.py
tests/test_struct/test_ofn/test_functional_owl.py
tests/test_struct/test_ofn/test_obo_to_ofn.py

Add language support to synonyms and literal property annotations

---

pyproject.toml
src/pyobo/struct/reference.py
tests/test_struct/test_obo/test_struct_term.py

ISO parsing wasn't generic enough, now try using a more general parser

Update date parsing

---

README.md
pyproject.toml
src/pyobo/api/__init__.py
src/pyobo/api/combine.py
src/pyobo/api/hierarchy.py
src/pyobo/api/names.py
src/pyobo/api/utils.py
src/pyobo/cli/lookup.py
tests/test_api.py

Switch hierarchy and name API to return references

---

pyproject.toml
tests/test_sources/test_meta.py
tests/test_struct/test_obo/test_struct_term.py

Follow-up to https://github.com/biopragmatics/bioregistry/pull/1413

Update EC tests

---

pyproject.toml
src/pyobo/_reference_tmp.py
src/pyobo/identifier_utils.py
src/pyobo/reader.py
src/pyobo/reader_utils.py
src/pyobo/registries/metaregistry.json
src/pyobo/struct/reference.py
src/pyobo/struct/struct_utils.py
tests/test_obo_reader/test_get.py
tests/test_struct/test_obo/test_struct_term.py
tests/test_utils/test_utils.py

1. Move around the Reference class for future upstreaming
2. Better passing around of exceptions to reduce logging on explicitly blacklisted identifiers
3. Improve exception handling for parsing URIs
4. Make passing around upgrade flags explicit
5. Add color!
6. This surfaces some new errors, see #354

Additional OBO reader refactoring

---

docs/source/cli.rst
docs/source/conf.py
docs/source/functional.rst
docs/source/index.rst
docs/source/installation.rst
src/pyobo/api/hierarchy.py
src/pyobo/getters.py
src/pyobo/reader.py
src/pyobo/sources/bigg/bigg_compartment.py
src/pyobo/sources/expasy.py
src/pyobo/sources/gmt_utils.py
src/pyobo/sources/go.py
src/pyobo/sources/gtdb.py
src/pyobo/sources/ncbi/ncbigene.py
src/pyobo/sources/uniprot/uniprot_ptm.py
src/pyobo/struct/functional/ontology.py
src/pyobo/struct/typedef.py
tests/test_obo_reader/test_reader_ontology.py
tests/test_utils/test_caches.py

Cleanup docs

---

src/pyobo/reader_utils.py
tests/test_obo_reader/test_reader.py

Implement comments in xrefs

---

src/pyobo/sources/expasy.py

Concatenate multiple DE lines.

---

pyproject.toml
src/pyobo/sources/expasy.py

Adding reactions as definitions.

---

src/pyobo/sources/chembl/chembl_target.py

sometimes, there are ENSG ensembl references, which caused an identifier validation error. This fixes it.
this also checks the type to us the more specific relationship types by re-ordering the conditional

Update ChEMBL target processor

---

src/pyobo/sources/bigg/bigg_metabolite.py
src/pyobo/sources/bigg/bigg_reaction.py
src/pyobo/sources/chembl/chembl_target.py
src/pyobo/sources/drugcentral.py
src/pyobo/sources/msigdb.py
src/pyobo/sources/nlm/utils.py
src/pyobo/sources/pharmgkb/pharmgkb_chemical.py
src/pyobo/sources/ror.py
src/pyobo/sources/signor/signor_complexes.py
src/pyobo/sources/slm.py

Address identifier validation issues

---

src/pyobo/sources/bigg/bigg_metabolite.py

1. Add top-level "molecule" from COB for universal BiGG metabolite IDs and annotate as root term on ontology
2. Better name generation

Further BiGG Metabolite updates

---

pyproject.toml
src/pyobo/cli/database_utils.py
src/pyobo/sources/cgnc.py
src/pyobo/sources/flybase.py
src/pyobo/sources/omim_ps.py
src/pyobo/sources/pharmgkb/pharmgkb_gene.py

This PR updates the getters for the following sources:
1. CGNC
2. FlyBase
3. OMIM PS

Resource updates

---

src/pyobo/sources/credit.py

Update contributor role taxonomy source

---

src/pyobo/sources/drugbank/drugbank.py
src/pyobo/sources/gwascentral/gwascentral_study.py

This adds some ignores on DrugBank and GWAS Central, since these resources are not possible to get atm

Address QA tests on broken resources

---

src/pyobo/sources/clinicaltrials.py

Follow-up to https://github.com/obi-ontology/obi/pull/1858 and https://github.com/obi-ontology/obi/issues/1831, part of #411
This PR rewires new OBI terms for clinical trials

Update clinical trial terms

---

src/pyobo/sources/iana_media_type.py
src/pyobo/struct/struct_utils.py

This PR does the following:
1. Adds a predicate connecting a media type to a file extension
2. Encodes file extensions as individuals

Update IANA media types

---

src/pyobo/struct/functional/obo_to_functional.py
src/pyobo/struct/obograph/export.py
src/pyobo/struct/struct.py
tests/test_struct/test_obo/test_struct_obo.py

Handle ontology IRI and ontology version IRI
