biopragmatics/pyobo

src/pyobo/registries/metaregistry.json
Partially addresses #41, by fixing a typo in synonyms.
=> Fix typo in metaregistry

setup.cfg, src/pyobo/__init__.py, src/pyobo/extract.py, src/pyobo/registries/metaregistry.json, src/pyobo/sources/drugbank.py, src/pyobo/sources/drugbank_salt.py, src/pyobo/struct/typedef.py
Closes #80
This PR does the following:
- adds `drugbank.salt` to the metaregistry
- adds a nomenclature for `drugbank.salt`
- adds the `obo:has_salt` relation between `drugbank` and `drugbank.salt` curies that goes into the DrugBank OBO
Ultimately, to get the drugbank to salt mapping, use:
```python
import pyobo
df = pyobo.get_filtered_relations_df('drugbank', 'obo:has_salt')
```
This has 3 columns - drugbank ID, target namespace prefix (always drugbank.salt), and target namespace prefix.
=> Add drugbank salt support

src/pyobo/sources/pubchem.py
This PR updates the PubChem version. It looks like their FTP server doesn't keep versions older than 4 months, and so the BASE_URL for the 2020-07-02 version doesn't exist anymore.
=> Update PubChem version

src/pyobo/apps/gilda/app.py, src/pyobo/apps/gilda/cli.py, src/pyobo/gilda_utils.py
This PR does the following:
1. Puts Gilda utilities in a top-level submodule instead of buried in the web app
2. Make it possible to make a gilda grounder with multiple prefixes
3. Enable using identifiers when generating gilda terms
Example run:
```bash
$ pyobo apps gilda -v efo clo cellosaurus depmap
```
=> Update Gilda code

setup.cfg, src/pyobo/api/alts.py, src/pyobo/api/metadata.py, src/pyobo/api/names.py, src/pyobo/api/properties.py, src/pyobo/api/relations.py, src/pyobo/api/species.py, src/pyobo/api/typedefs.py, src/pyobo/api/utils.py, src/pyobo/api/xrefs.py, src/pyobo/getters.py, tests/test_get.py
This PR improves the way that versions are looked up when getting resources. It doesn't expose these options on the top-level functions, though. It also better relies on `bioversions` for getting current version numbers
=> Update version handling

docs/source/conf.py, pyproject.toml, setup.cfg, src/pyobo/api/xrefs.py, src/pyobo/sources/hgnc.py, src/pyobo/sources/rhea.py, src/pyobo/struct/reference.py, src/pyobo/struct/typedef.py, tests/test_extract.py, tests/test_struct.py, tox.ini
Closes #155 
This PR enforces that all `References` are valid. It proactively removes bananas and fixes casing. After instituting this, some other data had to be modified, this is a great catch!
Relies on https://github.com/biopragmatics/bioregistry/pull/930.
=> Enforce all references are standardized

src/pyobo/api/names.py, src/pyobo/sources/cgnc.py, src/pyobo/sources/chembl.py, src/pyobo/sources/depmap.py, src/pyobo/sources/drugcentral.py, src/pyobo/sources/hgnc.py, src/pyobo/sources/mgi.py, src/pyobo/sources/mirbase_family.py, src/pyobo/sources/npass.py, src/pyobo/sources/ror.py, src/pyobo/sources/sgd.py, src/pyobo/sources/slm.py, src/pyobo/sources/zfin.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py
Closes #161 
Closes https://github.com/biopragmatics/obo-db-ingest/issues/6
This will ensure that the obo-db-ingest documents can be more readily merged with other OBO Foundry ontologies
This PR also sprinkles in descriptions and licenses when outputting OBO
=> Use preferred prefixes when outputting OBO flat files

src/pyobo/sources/famplex.py, src/pyobo/sources/rhea.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py
Closes #167
1. Add "has participant" relations between the "master" and "bidirected" reaction and ChEBI identifiers
2. Add has input / has output relations between directional reactions and ChEBI identifiers
3. Adds "enabled by" for UniProt and EC xrefs
4. Adds GO relations with newly minted `debio:0000047` (as a placeholder for the maybe results of https://github.com/oborel/obo-relations/issues/783)
5. Adds programmatically generated names for left-to-right, right-to-left, and bi-directed reactions
Example output:
```
[Term]
[Term]
id: rhea:11880
name: \(S\)-6-hydroxynicotine + H2O + O2 = 6-hydroxypseudooxynicotine + H2O2
relationship: RO:0000057 CHEBI:15377 ! has participant water
relationship: RO:0000057 CHEBI:15379 ! has participant dioxygen
relationship: RO:0000057 CHEBI:16240 ! has …
```
=> Improve Rhea import

src/pyobo/sources/uniprot/uniprot.py, src/pyobo/struct/typedef.py
Closes #172
This PR adds several additional fields to the uniprot export:
1. `ft_binding` - binding interactions
2. `xref_proteomes` - the `uniprot.proteome` reference(s?) from which a record is derived
3. `cc_function` a nice high-level description of the function of the protein
4. `go` GO terms associated with the protein (from all 3 hierarchies)
5. `xref_geneid` - NCBI Gene term from which a protein is produced
It also refactors the way the query URLs are constructed to be more easily extensible
=> Extend UniProt export

src/pyobo/api/names.py
This PR adds the ability to specify the version when passing names to `pyobo.get_name` and `pyobo.get_name_by_curie`.
Therefore, if you want to make a name getter that uses pinned versions, you can do something like this:
```python
import pyobo
VERSION_PINS = {"mesh": 2023}
def pinned_get_name_by_curie(curie: str) -> str | None:
prefix = curie.split(":")[0]
version = VERSION_PINS.get(prefix)
return pyobo.get_name_by_curie(curie, version=version)
```
=> Enable passing version to name getter

src/pyobo/sources/expasy.py
Closes #178
this pr adds some old code for updating EC, worth merging before re-releasing
=> Track obsoletions in EC

src/pyobo/api/alts.py, src/pyobo/api/hierarchy.py, src/pyobo/api/metadata.py, src/pyobo/api/names.py, src/pyobo/api/relations.py, src/pyobo/api/species.py, src/pyobo/api/typedefs.py, src/pyobo/api/xrefs.py, src/pyobo/aws.py, src/pyobo/cli/lookup.py, src/pyobo/constants.py, src/pyobo/sources/antibodyregistry.py, src/pyobo/sources/biogrid.py, src/pyobo/sources/ccle.py, src/pyobo/sources/mesh.py
Closes #183
I confirmed that the following code snippet works with internet disconnected. On my system , I had both MeSH 2023 and 2024 cached.
```python 
>>> import pyobo
>>> pyobo.get_name_by_curie('mesh:C039725', version='2023')
'Corynebacterium parvum vaccine'
```
=> Add version keyword to all lookup functions

src/pyobo/api/names.py, src/pyobo/api/utils.py, src/pyobo/cli/lookup.py, src/pyobo/constants.py, src/pyobo/sources/antibodyregistry.py, src/pyobo/sources/biogrid.py, src/pyobo/sources/hgnc.py, src/pyobo/sources/mesh.py, src/pyobo/sources/pubchem.py, src/pyobo/sources/rhea.py, src/pyobo/sources/uniprot/uniprot.py, src/pyobo/struct/struct.py, src/pyobo/utils/path.py, src/pyobo/xrefdb/sources/chembl.py, src/pyobo/xrefdb/sources/pubchem.py
This draft PR enables users to define a prefix to version mapping stored in an environmental variable: `VERSION_PINS` which will allow users to define the configured version they would like to use for a resource to avoid downloading new versions of the resource. The problem with the current argument-based approach is that in many settings PyOBO is being accessed indirectly so it would be very inconvenient to control versions via function arguments.
Places in the code where `bioversions.get_versions` is used has been replaced by `pyobo.api.utils.get_version` as we call `bioversions.get_versions` in  `pyobo.api.utils.get_version`.  Please let me know if this change is not needed.
=> Enable use of enviornmental variable version pin dictionary

src/pyobo/api/utils.py, src/pyobo/constants.py, tests/test_version_pins.py
This PR fixes a bug where `VERSION_PINS` is always set to an empty dictionary due to a misaligned indent. We also handle invalid prefixes and version datatypes more gracefully and make the logger more informative.
=> Fix version pins

src/pyobo/struct/struct.py
References biopragmatics/obo-db-ingest#13
Demonstration of results are in https://github.com/biopragmatics/obo-db-ingest/pull/12
This PR enables serializing to OBO but skipping object properties, as requested by @cmungall
=> Enable outputting slim OBO

src/pyobo/struct/struct.py, src/pyobo/utils/misc.py
This PR removes code from the `pyobo.utils.misc` module that has since been replaced by calls to `bioontologies.robot`
=> Reuse external robot wrapper

pyproject.toml, src/pyobo/getters.py, src/pyobo/sources/gwascentral_phenotype.py, src/pyobo/sources/hgnc.py, src/pyobo/sources/interpro.py, src/pyobo/sources/kegg/api.py, src/pyobo/sources/kegg/genes.py, src/pyobo/sources/kegg/genome.py, src/pyobo/sources/kegg/pathway.py, src/pyobo/sources/mesh.py, src/pyobo/sources/mirbase.py, src/pyobo/sources/pubchem.py, src/pyobo/sources/sgd.py, src/pyobo/sources/utils.py, src/pyobo/struct/struct.py, src/pyobo/utils/io.py, src/pyobo/utils/path.py
This PR does the following:
1. Updates to pystow 0.6.0, which upstreams handling of versions
2. Switches the `pyobo.utils.paths` functions to return `pathlib.Path`, and updates any code that that affected to use path objects instead of strings
3. Does some reorganizing of the KEGG code. It seems to be the case that the API isn't available without authorization anymore, so this isn't worth a lot of time to test
4. Moves an io function that's only used when handling mesh out of `pyobo.utils.io` and into the mesh source module
5. Gets rid of `pyobo.utils.paths.get_prefix_obo_path`, which is only used once
6. Gets rid of `pyobo.utils.paths.ensure_tar_df`, which is used only once
=> Update path utilities

src/pyobo/identifier_utils.py, src/pyobo/registries/metaregistry.json, src/pyobo/registries/metaregistry.py, tests/test_utils.py
This adds additional configuration into `metaregistry.json` that allows for resource-specific rules to be added. This is useful since there might be non-generally applicable transformations that are desired. For example, eNanoMapper ontology uses `Thesaurus:` as the prefix for `NCIT:`.
=> Add resource-specific remappings

src/pyobo/registries/metaregistry.py, src/pyobo/resources/goc.py, src/pyobo/resources/goc.tsv, tox.ini
Due to historical reasons, the Gene Ontology and related resources use an internal curator identifier space ``GOC`` instead of ORCID. This namespace is partially mapped to ORCID and is version controlled [here](https://raw.githubusercontent.com/geneontology/go-site/refs/heads/master/metadata/users.yaml>).
This module loads that namespace and uses :mod:`orcid_downloader` to try and add additional ORCID groundings. Then, this module is loaded in PyOBO's custom CURIE upgrade system so GOC CURIEs are seamlessly replaced with ORCID CURIEs, when possible.
See also https://github.com/geneontology/go-ontology/issues/22551
=> Implement GOC standardization

src/pyobo/sources/chembl.py, src/pyobo/sources/complexportal.py, src/pyobo/sources/cvx.py, src/pyobo/sources/drugbank.py, src/pyobo/sources/drugcentral.py, src/pyobo/sources/expasy.py, src/pyobo/sources/famplex.py, src/pyobo/sources/flybase.py, src/pyobo/sources/geonames.py, src/pyobo/sources/hgnc.py, src/pyobo/sources/icd10.py, src/pyobo/sources/interpro.py, src/pyobo/sources/kegg/genes.py, src/pyobo/sources/kegg/pathway.py, src/pyobo/sources/mirbase.py, src/pyobo/sources/msigdb.py, src/pyobo/sources/pathbank.py, src/pyobo/sources/pombase.py, src/pyobo/sources/ror.py, src/pyobo/sources/slm.py, src/pyobo/sources/uniprot/uniprot.py, src/pyobo/struct/struct.py
Right now, PyOBO uses object properties for everything, even when it should be using annotation properties. This PR adds a new interface for better annotating when annotation properties have a CURIE reference as their object. It doesn't yet change any functionality - that will come in a subsequent PR.
=> Improve annotation and object property adders

src/pyobo/api/alts.py, src/pyobo/api/metadata.py, src/pyobo/api/names.py, src/pyobo/api/properties.py, src/pyobo/api/relations.py, src/pyobo/api/species.py, src/pyobo/api/typedefs.py, src/pyobo/api/xrefs.py
This adds the `force_process` flag in addition to the already existing `force` flag - the `force` flag causes re-download and reprocess. `force_process` only causes reprocess, which saves a lot of time for many resources.
=> Enable passing a flag for reprocessing

src/pyobo/api/alts.py, tests/test_alt_ids.py
This PR starts moving away from using the `normalize_curie` function in alt id lookup. It also does a bit of refactoring and adds additional tests
=> Improve alternative identifier lookup functions

src/pyobo/api/relations.py, src/pyobo/struct/__init__.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py, tests/test_get.py
This PR reduces code where there was a separate "RelationHint" that had duplicate handling for strings/references/terms
=> Streamline relation string handling

src/pyobo/api/alts.py, src/pyobo/api/metadata.py, src/pyobo/api/names.py, src/pyobo/api/properties.py, src/pyobo/api/relations.py, src/pyobo/api/species.py, src/pyobo/api/typedefs.py, src/pyobo/api/utils.py, src/pyobo/api/xrefs.py, src/pyobo/cli/database.py, src/pyobo/cli/database_utils.py, src/pyobo/cli/lookup.py, src/pyobo/constants.py, src/pyobo/getters.py, src/pyobo/gilda_utils.py, src/pyobo/xrefdb/canonicalizer.py, src/pyobo/xrefdb/xrefs_pipeline.py, tests/test_mapper.py
All of the functions in the API (e.g. for getting names, alternative IDs, descriptions) have the same API where you can pass `force`, `force_process`, `version`, etc.
This PR enforces that these really are standardized by using variadic keyword arguments to pass them around in combination with some clever type annotations. These annotations use a combination of `Unpack` and typed dicts to enforce the functions work the same, without duplicating. It also makes it possible to add additional arguments in bulk later.
This abstraction has the minor drawback that it's a bit less transparent, but this significantly reduces the code complexity.
=> Refactor API interface

src/pyobo/struct/struct.py, tests/test_struct.py
1. Reformat the way properties are emitted from a Term object to reduce code
2. Add a reusable way of warning for undefined typedefs
=> Update typedef handling

src/pyobo/cli/lookup.py, src/pyobo/identifier_utils.py, src/pyobo/reader.py, src/pyobo/struct/reference.py, src/pyobo/struct/typedef.py, tests/test_get.py
1. Standardize usage in `lookup.py` to go through `pyobo.Reference.from_curie`
2. Expose extra option through `TypeDef.from_curie` for specifying ontology prefix
3. Refactor construction of missing prefix errors by passing the reference node through
4. Change default typedef handling to be more consistent with OWLAPI
=> Update CURIE parsing utilities

src/pyobo/obographs.py, src/pyobo/reader.py, src/pyobo/struct/struct.py, tests/test_get.py, tests/test_reader.py, tests/test_struct.py
This PR introduces some breaking changes:
1. it fixes many bugs in the handling of properties, so the results will change drastically in some cases
2. splits storage into two new dictionaries - `annotations_literal` and `annotations_object`
3. removes the `Term.append_property` function and replaces it with two new ones for the two different dictionaries
4. Changes the datatypes in several of the iterators
5. Adds datatype handling for annotation properties
=> Breaking: update handling of properties

src/pyobo/__init__.py, src/pyobo/sources/cvx.py, src/pyobo/sources/expasy.py, src/pyobo/sources/gtdb.py, src/pyobo/sources/hgnc.py, src/pyobo/sources/interpro.py, src/pyobo/sources/mgi.py, src/pyobo/sources/msigdb.py, src/pyobo/sources/pombase.py, src/pyobo/sources/rgd.py, src/pyobo/sources/rhea.py, src/pyobo/sources/slm.py, src/pyobo/sources/uniprot/uniprot.py, src/pyobo/struct/__init__.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py, tests/test_get.py, tests/test_struct.py
1. Move the default_reference function so it can be more widely reused
2. Add a companion function for escaping a default reference (i.e., show `has_part` instead of obo:chebi#has_part` on OBO export in chebi)
3. Make property typedefs explicit in several sources
4. Require synonym typedefs to have names. Default to empty string if note
5. Update several sources to better use annotation properties
=> Make data model more explicit

src/pyobo/reader.py, tests/test_reader.py
1. refactor into own function to reduce code complexity
2. change order to reduce warnings that didn't make sense (don't say there's an issue with no datatype when parsing a reference)
=> Streamline property parsing

src/pyobo/api/alts.py, src/pyobo/cli/lookup.py, src/pyobo/reader.py, src/pyobo/sources/complexportal.py, src/pyobo/sources/conso.py, src/pyobo/sources/famplex.py, src/pyobo/sources/flybase.py, src/pyobo/sources/uniprot/uniprot.py, src/pyobo/sources/uniprot/uniprot_ptm.py, src/pyobo/sources/zfin.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py, tests/test_get.py, tests/test_reader.py, tests/test_struct.py
1. Rename Reference.from_curie to Reference.from_curie_to_uri. This has the benefit that it can be typed differently, and also reflects its different functionality from the base class.
2. Updated node iteration to directly construct references. This reduces some superfluous code in indexing them in a mapping
3. Pass `ontology_prefix` through to functions where it was missed
=> Streamline URI and CURIE parsing in the reader

src/pyobo/reader.py, src/pyobo/struct/struct.py, tests/test_get.py, tests/test_reader.py, tests/test_struct.py
1. Switch storage in the Synonym class to only keep a reference to the synonym type definition
2. Add warnings when a synonym type definition isn't defined in the ontology but you try outputting it to OBO lines
=> Improve synonym and synonym typedef handling

src/pyobo/getters.py, src/pyobo/identifier_utils.py, src/pyobo/reader.py, src/pyobo/reader_utils.py, src/pyobo/struct/reference.py, tests/test_get.py, tests/test_reader.py
This PR introduces a new function that consolidates parsing when an unprefixed identifier should be tried to be grounded against RO/BFO.
It also does a bit of renaming to make the diff easier to read
=> Improve typedef parsing

src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, tests/test_struct.py
This fixes an issue where default terms of the form of `obo:<prefix>#<identifier>` weren't properly serialized to OBO flat file
=> Fix default reference output in OBO flat file format

src/pyobo/sources/__init__.py, src/pyobo/sources/gard.py
=> Add GARD as a source

src/pyobo/sources/gtdb.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py, tests/test_reader.py, tests/test_struct.py
This will support making more SSSOM-like mappings through the PyOBO DSL. 
Specifically, it will support @jplfaria to annotate some extra information into GTDB (see the TODO in the GTDB source)
Note that most of the functionality and data structures are implemented as private methods and fields. These are subject to change.
=> Implement axioms on relations, object properties, and xrefs

src/pyobo/reader.py, src/pyobo/struct/struct.py, tests/test_reader.py
1. Fix bug to output correctly normalized "default" references
2. Add reading for property values with custom handling for root terms
3. Still TODO - handle reading "default" references
=> Improve root term handling

src/pyobo/obographs.py, src/pyobo/reader_utils.py, src/pyobo/struct/__init__.py, src/pyobo/struct/struct.py
- Update to using `curies` builtins
- Remove unnecessary exports for replaced type hints
=> Improve type annotations for synonym specificity

src/pyobo/reader.py, src/pyobo/struct/struct.py, src/pyobo/struct/struct_utils.py, src/pyobo/struct/typedef.py, src/pyobo/struct/vocabulary.py, tests/test_get.py, tests/test_reader.py, tests/test_reader_ontology.py, tests/test_reader_typedef.py, tests/test_struct.py, tests/test_typedef.py
This PR mostly completes the reader and data structures for terms and typedefs with respect to the OBO flat file format.
It's still not quite accurate in the way it represents instances, but this is hard to deal with since ROBOT cowardly refuses to work with instances in OBO format. The functional OWL PR will make it easier to test this
=> Add additional features to parser

src/pyobo/obographs.py, src/pyobo/struct/struct.py
This PR removes the `xref_types` variable from the Term class, because there are now alternate ways of adding mappings and getting them back out, see `Term.get_mapping`
=> Remove xref-types

src/pyobo/api/properties.py, src/pyobo/reader.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct.py, src/pyobo/struct/struct_utils.py
This PR adds an intermediate function that enables `curies.Reference`s to be used more widely (though, does not yet carefully update the type annotations)
=> Make use of preferred CURIEs more consistent

src/pyobo/sources/icd11.py, src/pyobo/sources/icd_utils.py
This PR adds ICD11 MMS codes as ad-hoc properties. Later, it can create proper mappings once a prefix is decided for the codes.
Note that not all ICD11 identifiers have an MMS code
Here's an example from the top of the written OBO:
```
format-version: 1.4
auto-generated-by: PyOBO v0.12.0-dev-b06b9d0d on 2025-01-09T14:51:39.588002
idspace: dcterms http://purl.org/dc/terms/ "Dublin Core Metadata Initiative Terms"
idspace: skos http://www.w3.org/2004/02/skos/core# "Simple Knowledge Organization System"
ontology: icd11
property_value: dcterms:title "International Classification of Diseases\, 11th Revision" xsd:string
property_value: dcterms:license "CC-BY-ND-3.0-IGO" xsd:string
property_value: dcterms:description "Diagnostic tool for epidemiology\\\, health management and clinical …
```
=> Import ICD11 MMS codes

src/pyobo/sources/icd11.py
cc @matentzn 
now, the ICD11 OBO output looks like:
```
format-version: 1.4
auto-generated-by: PyOBO v0.12.0-dev-86e8399e on 2025-01-09T17:15:55.878453
idspace: dcterms http://purl.org/dc/terms/ "Dublin Core Metadata Initiative Terms"
idspace: skos http://www.w3.org/2004/02/skos/core# "Simple Knowledge Organization System"
ontology: icd11
property_value: dcterms:title "International Classification of Diseases\, 11th Revision" xsd:string
property_value: dcterms:license "CC-BY-ND-3.0-IGO" xsd:string
property_value: dcterms:description "Diagnostic tool for epidemiology\\\, health management and clinical purposes\\\, maintained by the World Health Organization \\\(WHO\\\). It provides a system of diagnostic codes for classifying diseases\\\, including nuanced classifications of a wide variety …
```
=> Generate SSSOM for ICD11 to ICD11 codes

src/pyobo/struct/struct.py
- make it possible to pass args into the CLI getter, this makes it easier to debug for situations where you want to write `HGNCGetter.cli(["--owl"])`
- refactor configuration of cache into its own function
- add flag to turn off writing of cache
=> Update auto-generated ontology CLI

src/pyobo/sources/bigg/bigg_metabolite.py, src/pyobo/sources/bigg/bigg_reaction.py, src/pyobo/sources/rhea.py, src/pyobo/struct/functional/dsl.py, src/pyobo/struct/struct.py, src/pyobo/struct/typedef.py, src/pyobo/struct/vocabulary.py, tests/test_struct/test_obo/test_typedef.py
1. It seems like the debio issue is getting closer to being solved, but somehow the chemrof predicates seem to work where the debio ones don't for InChI and SMILES. debio predicates also seem to work in the miRBase exporter when used for object properties.
2. Skip more bad IDs from BiGG
3. Output oboInOWL to OFN if auto-generated-by is used, but not in OBO since it's builtin
=> Additional improvements for OFN output

src/pyobo/getters.py, src/pyobo/reader.py, tests/test_obo_reader/test_get.py
This PR makes sure that the parsed obonet file is actually cached. It also makes sure the tests don't pollute the active cache directory
=> Fix obonet caching

src/pyobo/sources/chembl/chembl_compound.py, src/pyobo/sources/cvx.py, src/pyobo/sources/drugbank/drugbank.py, src/pyobo/sources/drugcentral.py, src/pyobo/sources/geonames/geonames.py, src/pyobo/sources/hgnc/hgnc.py, src/pyobo/sources/icd/icd10.py, src/pyobo/sources/interpro.py, src/pyobo/sources/msigdb.py, src/pyobo/sources/pathbank.py, src/pyobo/sources/pombase.py, src/pyobo/sources/slm.py, src/pyobo/struct/reference.py, src/pyobo/struct/struct_utils.py, tests/test_struct/test_obo/test_struct_term.py
This PR adds `Stanza.annotate_X` for common datatypes and makes `Stanza.annotate_literal` only take OBO literals. This will make it easier to extend the OBO literal interface, e.g., with language codes
=> Update interface for `Stanza.annoate_literal`

src/pyobo/sources/gtdb.py
In the current implementation the species level GTDB terms have mappings to NCBI taxonomy IDs. This is done by retrieving the NCBI taxon IDs from the column ```ncbi_taxid``` in the source files:
```
#: AR stands for archea
GTDB_AR_URL = "https://data.gtdb.ecogenomic.org/releases/latest/ar53_metadata.tsv.gz"
#: BAC stands for bacteria
GTDB_BAC_URL = "https://data.gtdb.ecogenomic.org/releases/latest/bac120_metadata.tsv.gz"
```
I recently realized there is a specific column named ```ncbi_species_taxid``` and that the current ```ncbi_taxid``` doesnt always represent NCBI taxonomy at the species level. The correct column ```ncbi_species_taxid``` should be the one used for this purpose. 
I want to use ```ncbi_taxid``` for a different purpose but that will be part of a different PR/discussion. …
=> Update column for species in GTDB source

src/pyobo/sources/bigg/bigg_compartment.py, src/pyobo/sources/bigg/bigg_metabolite.py, src/pyobo/sources/bigg/bigg_model.py, src/pyobo/sources/bigg/bigg_reaction.py, src/pyobo/sources/credit.py, src/pyobo/sources/expasy.py, src/pyobo/sources/geonames/features.py, src/pyobo/sources/geonames/geonames.py, src/pyobo/sources/gtdb.py, src/pyobo/sources/ncbi/ncbi_gc.py, src/pyobo/sources/nlm/nlm_catalog.py, src/pyobo/sources/nlm/nlm_publisher.py, src/pyobo/sources/ror.py, src/pyobo/struct/struct.py
Closes #333 by doing the following:
1. Remove all manual IDSPACE definitions from PyOBO sources. This means that the Bioregistry will be used to look up all URI prefixes. This functionality was added in #291
2. Update the way URI prefixes are looked up from the Bioregistry to use the RDF URI prefix as a higher priority before anything else
This means we can upstream all discussions about the expansions into the Bioregistry repo
=> Improve IDSPACES for sources

src/pyobo/reader.py, tests/test_obo_reader/test_reader.py
This enables sitauations like the following, where quotes are omitted, but a trailing (superfluous) datatype is set.
```
ontology: ro
[Term]
id: RO:0002160
property_value: IAO:0000119 PMID:17921072 xsd:string
```
This is relevant for `ceph` (and many others)
```
ceph - Cephalopod Ontology
2025-02-05 23:29:27 WARNING  [obo:ceph - dc:source] could not parse object: http://www.sil.si.edu/smithsoniancontributions/zoology/pdf_hi/sctz-0513.pdf xsd:anyURI                                                        
2025-02-05 23:29:27 WARNING  [ro:0002160 - iao:0000119] could not parse object: PMID:17921072 xsd:string                                                                                                                  
2025-02-05 23:29:27 WARNING  [ro:0002160 - iao:0000119] could not parse …
```
=> Handle annotation objects with superfluous datatypes

pyproject.toml, src/pyobo/api/edges.py, src/pyobo/api/properties.py, src/pyobo/sources/pharmgkb/utils.py, src/pyobo/struct/reference.py, tests/test_struct/test_reference.py, tox.ini
- Reuse new base class from `curies.NamableReference`
- Remove redundant prefix validation
=> Refactor `pyobo.Reference`

src/pyobo/reader.py, src/pyobo/struct/reference.py
Improve error handling in 3 cases:
1. Handle incorrect `treat-xrefs-as-genus-differentia` lines, which happens in `plana`
2. Handle unparsable dates, which happens in `nomen`
3. Handle validation of ill-defined default values, which happens in `geno`
4. Additional typing cleanup for OBO Literal construction
=> Improve error handling in reader

src/pyobo/reader.py, tests/test_obo_reader/test_reader_ontology.py
This makes sure that property values with URIs in quotes can get parsed properly
=> Update URI parsing

pyproject.toml, src/pyobo/__init__.py, src/pyobo/api/combine.py, src/pyobo/api/names.py, src/pyobo/gilda_utils.py, src/pyobo/ner/__init__.py, src/pyobo/ner/api.py, src/pyobo/struct/struct.py, src/pyobo/struct/struct_utils.py, tests/test_api.py
As a follow-up to #345, this upstreams even more functionality for wrapping NER and storing literal mappings in a generic way to the SSSLM package
=> Switch to SSSLM

src/pyobo/sources/expasy.py, src/pyobo/struct/__init__.py, src/pyobo/struct/typedef.py
References #186
This PR adds a `dcterms:source` property to the EC export to make it clear that it comes from ExPASy and not enzyme-database.org. This is just historical - we can rewrite it to ingest the other one in a future update.
cc @cmungall 
```
format-version: 1.4
data-version: 2025-02-05
auto-generated-by: PyOBO v0.12.0-dev-1f6792ff on 2025-03-06T09:13:20.732577
idspace: EC https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec= "Enzyme Nomenclature"
idspace: dcterms http://purl.org/dc/terms/ "Dublin Core Metadata Initiative Terms"
idspace: uniprot http://purl.uniprot.org/uniprot/ "UniProt Protein"
ontology: ec
property_value: dcterms:title "Enzyme Nomenclature" xsd:string
property_value: dcterms:license "CC-BY-4.0" xsd:string
property_value: dcterms:description "The Enzyme …
```
=> Add source annotation to EC

src/pyobo/api/alts.py, src/pyobo/api/edges.py, src/pyobo/api/metadata.py, src/pyobo/api/names.py, src/pyobo/api/properties.py, src/pyobo/api/relations.py, src/pyobo/api/species.py, src/pyobo/api/typedefs.py, src/pyobo/api/xrefs.py, src/pyobo/aws.py, src/pyobo/constants.py, src/pyobo/struct/struct.py, src/pyobo/utils/path.py, src/pyobo/xrefdb/sources/intact.py
1. Use an enum for names of caches / files associated with them
2. Simplify synonym cache lookup to rely on literal mappings
3. Simplify filtered xref cache lookup to rely on full xref df and just make a filter
=> Streamline cache path generation

src/pyobo/api/hierarchy.py, src/pyobo/api/xrefs.py, src/pyobo/struct/struct.py, tests/test_api.py
The `get_xrefs()` function has been deprecated - this is a step towards replacing the implementation with the SSSOM-based one
=> Reimplement getting xrefs

src/pyobo/identifier_utils/api.py
This helps deal with issues with URLs in DOID (and potentially other places)
=> Remove trailing slash from URLs
